### ISSUE TITLE
[BUG] 3.5rc7 rightclick drag scales brush without modifier pressed

### ISSUE THREAD

**Issue by Flavelius** [dreadpon/godot_spatial_gardener#12]
**Godot version**
3.5rc7 mono official

**Plugin version**
current git repository state (7b127ade841c7b2fc8ccfd34f4cbb46fb2bb33d6)

**Platform**
Windows 10

**Issue description**
While having the Gardener selected, rightclick-drag scales the brush instead of adjusting the view (3D editor camera rotation). This happens even though in the gardener settings it says shift as modifier is required; and setting this to another modifier like control also doesn't change anything.
My 3D editor navigation scheme is maya, maybe that matters:
![grafik](https://user-images.githubusercontent.com/8841352/181369885-b6b3ca70-e417-4470-9ed2-39ededef8f3c.png)
![grafik](https://user-images.githubusercontent.com/8841352/181370385-7bac3d1e-f4e5-4e0b-b925-db0253d16c02.png)

**Steps to Reproduce**
maybe it's reproducable with the settings from the screenshot, not sure.

**Minimal reproduction project**
This is more an editor-settings/addon problem than a project-problem

**Comment by Flavelius** [comment]
Oh, i misunderstood the settings. the lower "Brush Property Edit Button" is parameter 1 in the paint panel, the '~..Modifier Key' one is for parameter 2. 
I can change the mouse button to middle mouse (and that works).
Sorry for bothering.

**Comment by dreadpon** [comment]
:3

**Comment by Flavelius** [comment]
Maybe renaming them would be an improvement in general. I still would understand them to be a key-combination (as they share a large part of their name)
