### ISSUE TITLE
Add option to change size of multi mesh instances used to decrease draw calls for dense foliage

### ISSUE THREAD

**Issue by LeonStansfield** [dreadpon/godot_spatial_gardener#14]
I am working on an action game with dense grass and foliage on the ground in medium-sized levels. 
I notices using your plugin that the multi mesh instances used are often incredibly small, only being about 1-2 metres wide. This is leading to problems with draw calls in my game where too many mmu's are being drawn, which could be massively reduced if the size of each mmu was larger.
There could be a slider for multi mesh instance size which sets how large the multi mesh instances are, with a larger number meaning larger mmu's and lower draw calls, at the expense of a more chunky border at the LOD max and LOD kill distances.

I have no idea how to actually implement this.

**Comment by dreadpon** [comment]
Have you tried reconfiguring the octrees?
There you can increase the number of instances to fit inside an MMI, which will implicitly increase the size of your multimeshes.
If you are able to derive a minimum size you consider optimal, you can also try setting _that_. That way your MMIs won't ever be smaller than the size you chose.
