### ISSUE TITLE
Plugin broken on godot 3.5 'problem with plugin.GD'

### ISSUE THREAD

**Issue by LeonStansfield** [dreadpon/godot_spatial_gardener#17]
Godot 3.5 mono windows 64

plugin version 1.0.0

Windows 11 device

The plugin will not enable in godot 3.5 mono with the text: 'Unable to load addon script from path: 'res://addons/dreadpon.spatial_gardener/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/dreadpon.spatial_gardener/plugin.cfg' to prevent further errors.'

I have checked plugin.gd and it has the error: (16,48) couldn't fully preload the script, possible cyclic reference or compilation error. use "load()" instead if a cyclic reference is intended.'

This error is on the line referencing the garderner.gd file. When I opened that fine I received the same error about line 18, referencing the defaults script. The defaults script had the same error at line 9 referencing the toolshed script, which had the same error at line 11 referencing the toolshed_brush script which has the error message "Script isn't fully loaded (cyclic preload?)"

To reproduce attempt to add the plugin on the 3.5 mono version of godot.

**Comment by Flavelius** [comment]
This is related to this issue: https://github.com/dreadpon/godot_spatial_gardener/issues/8
The signal should probably be generally removed now, as 3.5 is out officially

**Comment by dreadpon** [comment]
There are a number of things I'd like to implement, including fixing this and making a proper 3.5 release.
I'll get on it soon.

**Comment by dreadpon** [comment]
For now, closing it in favor of #8.
