### ISSUE TITLE
Cyclic dependency error in linux

### ISSUE THREAD

**Issue by magicalogix** [dreadpon/godot_spatial_gardener#20]
Godot 3.5

Spatial Gardener 1.0.0

Linux

I tried installing the plugin through the asset lib and also by downloading it directly but failed every time with a cyclic dependency error.

To reproduce the error just try installing the plugin through the asset library.

**Comment by dreadpon** [comment]
Please copy the exact error that is printed.

Also, have you tried relaunching the editor after failed installation and trying to enable it through project settings?

**Comment by dreadpon** [comment]
Will assume it's a problem described in issues above.
