### ISSUE TITLE
[BUG] Density setting doesnt change anything

### ISSUE THREAD

**Issue by Favkis** [dreadpon/godot_spatial_gardener#25]
**Godot version**
v3.5.stable.official [991bb6ac7]

**Plugin version**
1.1.0

**Platform**
Windows 10

**Issue description**
Density Setting doesnt change anything

**Steps to Reproduce**
I followed youtube tutorial https://www.youtube.com/watch?v=AqRz0URe3bo&list=PLtsfK5HW0bX-TKR8eO_uKEguii8w9dGIh&index=1
And when painting density is really sparce for grass, so I tried increasing density, but it does nothing, I tried restarting godot engine, still same issue, both in editor and game 
![image](https://user-images.githubusercontent.com/46406204/189140890-27ae51c5-afd1-4f17-887d-5d4825b15731.png)

**Comment by dreadpon** [comment]
I've created a fresh scene and tried drawing with brush size from your screenshot - 6.41 units.
1. I painted at low density `100` to get the feel of if
2. I switched to your density `1880.9`
3. I cranked it up to `10 000`
4. And finally with `100 000`

![Снимок экрана (637)](https://user-images.githubusercontent.com/35217125/189149977-38a7d12a-ca7e-4e38-832a-2d304723e475.png)

For now I assume your scene's scale is not very big and thus you need _way_ bigger density.

Try cranking it up and tell me the result. It would be best if you show me a comparison side by side of different densities.

**Comment by Favkis** [comment]
![image](https://user-images.githubusercontent.com/46406204/189157952-d77d7187-2a21-4c3c-ac6a-0cef0ab16f33.png)
ohhhhhh I can go further than 2000 that explains everything... tyyy didnt realise that... 😅😅

**Comment by Favkis** [comment]
also i didnt change anything to fix it not painting, I jsut uploaded video, tried again and it worked

**Comment by dreadpon** [comment]
> I tried to show you the issue, created gardener again but now it wont paint at all

Sounds like a collision issue. In-editor collision can be finicky sometimes. Reloading a scene usually helps. 

Anyway, glad this is solved!
BTW, you can increase slider limit in the project settings. Both for density and brush size if you need to.
