### ISSUE TITLE
Can't find Spatial Gardener via the AssetLib tab

### ISSUE THREAD

**Issue by golddotasksquestions** [dreadpon/godot_spatial_gardener#26]
**Godot version**
3.5 stable

**Platform**
Win

**Issue description**
I was about to comment on Reddit how easy it is to download and install Spatial Gardener from within Godot, but it turns out it is actually not that straight forward and might be missed by someone who does not decide to dig a little deeper.

In the AssetLib tab "Spatial Gardener" won't show up ...

![image](https://user-images.githubusercontent.com/47016402/189499359-830fca1e-3bcd-4d28-ad81-7174753c00a0.png)

... unless the user clicks on "Support" (which does _not_ look like a Button), and the enables "Testing". Only then Spatial Gardener shows up:

![image](https://user-images.githubusercontent.com/47016402/189499314-a0e1b6f8-61ae-465f-a3ac-f99dacf087f4.png)

**Steps to Reproduce**
In the Godot 3.5 stable Editor, go the the AssetLib tab and search for "Spatial" or "Spatial Gardener" or "Gardener" ...
What ever you do, Spatial Gardener won't show up.

"Testing" was disabled for me by default.

**Comment by dreadpon** [comment]
Huh. That's weird. I'll look into it

**Comment by dreadpon** [comment]
For some reason it was assigned the "Testing" tag, which is meant for pre-releases and beta tests.
Changing tags is a manual process conducted by the AssetLib moderators. 
It is now assigned the intended "Community" tag and is searchabble on the AssetLib.

Thanks for catching it!
