### ISSUE TITLE
Bad looking orange selection's bounding box when using the brush

### ISSUE THREAD

**Issue by DxUr** [dreadpon/godot_spatial_gardener#31]
**Godot version**
4.1.1

its not the big problem I fix it by just just adding a holder node as a parent of paint_brush_node

replace this line : 

owned_spatial.add_child(paint_brush_node)

with this:

var holder:Node = Node.new()
owned_spatial.add_child(holder)
holder.add_child(paint_brush_node)

**Comment by dreadpon** [comment]
Could you please provide a screenshot to illustrate what you mean by "selection area" and "ugly"?

**Comment by DxUr** [comment]
![image](https://github.com/dreadpon/godot_spatial_gardener/assets/137767403/2f3ae2e8-e4d6-4ebe-a5c0-26ca488c8f2c)
after fixing it:
![image](https://github.com/dreadpon/godot_spatial_gardener/assets/137767403/4d24048e-cbac-465c-ade5-45b07f98227a)

**Comment by dreadpon** [comment]
Weird that it works. Shouldn't the holder node account for selection's bounding box also?
I'll have to try it myself in my free time

**Comment by DxUr** [comment]
as it a node not a node3d

**Comment by dreadpon** [comment]
Not sure how I feel about that. I'll have to research if it may cause potential problems with transforms and node hierarchy first...

**Comment by DxUr** [comment]
I tested it, and it works perfectly.

**Comment by dreadpon** [comment]
Looks good on my side, implemented in [9a4c89f].
