### ISSUE TITLE
[BUG] buffer_update: Buffer argument is not a valid buffer of any type.

### ISSUE THREAD

**Issue by wladi0097** [dreadpon/godot_spatial_gardener#33]
**Godot version**: v4.1.1
**Plugin version**: v1.3.0-stable (c17f838)
**Platform**: Windows 10

**Issue description**
Maybe related to #32 or maybe to https://github.com/godotengine/godot/issues/68592 ?
Every time the MMI_container has more than one MuiltimeshInstance3D it throws following error on loading of the map:
````
E 0:00:03:0011   buffer_update: Buffer argument is not a valid buffer of any type.
  <C++ Error>    Method/function failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:5858 @ buffer_update()
````
[Err thrown in here](https://github.com/godotengine/godot/blob/bd6af8e0ea69167dd0627f3bd54f9105bda0f8b5/drivers/vulkan/rendering_device_vulkan.cpp#L5858) 

**Steps to Reproduce**
1. Add at least two plants
2.  run the scene.

**Minimal reproduction project**
Funny enough is that I cannot reproduce this in any small project this only happens in my bigger one. And if I delete the second plant everything works as expected.

**Comment by dreadpon** [comment]
Fixed by [4d96dc7] as mentioned in #32.
Thank you for pointing out a relevant Godot issue.
If this error persists on your side, please continue discussion in #32.
