### ISSUE TITLE
[BUG] LOD Kill Distance

### ISSUE THREAD

**Issue by MYNAMEISRADU** [dreadpon/godot_spatial_gardener#36]
**Godot version**
4.2.1 stable

**Plugin version**
1.3.1

**Platform**
Windows 10

**Issue description**

Objects with LOD Kill Distance greater than 0 get completely removed from the scene if you save the scene while the editor viewport camera is outside of the kill distance range and then reload the project 

**Steps to Reproduce**
1. Create a new Godot Project
2. Import the add-on to the Project (I am using the version of the plugin with the demo)
3. Create a new scene with a StaticBody3D as the floor (I'm just using a box mesh with 100x100 side and boxcollision3d with the same size)
4. Add a gardener to the scene and any plant (I'm using the tree generic lod 0) and increase the LOD Kill Distance to any value.
5. Zoom out until the plants are no longer visible, save the scene and reload the project.
6. The objects are now gone even if you zoom in, and on the right hand side the gardener shows "0" for the plants instantiated

**Comment by dreadpon** [comment]
Consolidating into #37
