### ISSUE TITLE
[BUG]Unable to load addon script from path: 'res://addons/dreadpon.spatial_gardener/plugin.gd'. 

### ISSUE THREAD

**Issue by Elmapul** [dreadpon/godot_spatial_gardener#4]
Godot v3.4.2.stable.mono.oficial [45eaa2daf]
OS: Ubuntu 18.04

godot_spatial_gardener_demo_v1.0.0-stable.zip

[godot_spatial_gardener_demo_v1.0.0-stable.zip](https://github.com/dreadpon/godot_spatial_gardener/releases/download/v1.0.0/godot_spatial_gardener_demo_v1.0.0-stable.zip)
"0.1.0 (3283e07), etc."

Unable to load addon script from path: 'res://addons/dreadpon.spatial_gardener/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/dreadpon.spatial_gardener/plugin.cfg' to prevent further errors.

**Comment by dreadpon** [comment]
Does the editor tell anything else? Or perhaps the console mentions the specific line where the error occurs? Does restarting the editor affect this issue somehow?

**Comment by Elmapul** [comment]
well, that is strange, i closed godot and opened again, and the bug was still there, but then, i deleted the file and extracted the zip again, and now it seems to be working fine...

so... sorry but im having trouble reproducing the bug on the first time i tried to extract it (on the file extracting program) , so maybe the problem isnt related to your code?
im not sure.
i will close the issue for now, hopefully no one will face it again.
