### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lmorao** [dreadpon/godot_spatial_gardener#41]
*v4.2.1.stable.official [b09f793f5]*

**Plugin version**
"1.3.1 [83def9caa75b53d8e9e5ce6abb3fa39546a2718e]"

**Platform**
*mac*

**Issue description**
*Describe your issue. What is expected to happen? What actually happened?*
When I paint with the gardener, I paint. When I save and reload the project, the painted changes are gone.
If I open the tscn I see the objects are there, and the moment the project is reloaded, they disapear from the tscn.

**Steps to Reproduce**
*Describe steps for others to reproduce this issue*
I don't have many steps... I installed the plugin, then I added the gardener, I added a static object on the same collision layer. I added the root folder for the gardener, then I added a plant and added a tscn to the plant (I did not add a .mesh). Then I painted, saved, reloaded the project.

**Minimal reproduction project**
*If applicable, please paste a link to minimal reproduction project that shows this issue in action.*
[gardener_reload_issue.zip](https://github.com/dreadpon/godot_spatial_gardener/files/14806908/gardener_reload_issue.zip)

**Comment by dreadpon** [comment]
Live in v1.3.2, solved in https://github.com/dreadpon/godot_spatial_gardener/issues/37
