### ISSUE TITLE
[FEATURE REQUEST] Add .res to open mesh dialog

### ISSUE THREAD

**Issue by aXu-AP** [dreadpon/godot_spatial_gardener#47]
Sorry for spamming you with all these requests, I think this tool is already very good and I'm finding relatively small nitpicks but I thought I should write them up anyway 😂

**Describe the problem you're trying to solve in your project**
I'm using binary .res resources to save meshes instead of text based .tres. When adding meshes the open file dialog shows only .tres files by default. I need to change the filter to all files instead (showing also bunch of unrelated files as well). It's not a showstopper, just a little annoyance.

**Describe a feature you consider and how it will help you**
Add .res files to the open dialog default filter.

**Describe alternatives you've considered**
Workaround is to use all files filter, which is a few extra clicks each time I import a new model.

**Describe how you imagine it would work. With code, pseudo-code, diagram or a drawing**
In open mesh dialog add *.res to the available filters.

**Comment by dreadpon** [comment]
Implemented in https://github.com/dreadpon/godot_spatial_gardener/commit/28af3e4c5b6f99f17b54b9316a1390401c196028
(Also added .obj and .scn/.gltf to scene open dialog)

**Comment by aXu-AP** [comment]
Thanks!
