### ISSUE TITLE
[FEATURE REQUEST] Enable deleting floating instances

### ISSUE THREAD

**Issue by Flavelius** [dreadpon/godot_spatial_gardener#5]
**Describe the problem you're trying to solve in your project**
I'm not trying to solve a problem in my project; it's just something that can become a problem.
When painting vegetation onto a mesh that later changes, instances can end up floating in the air.
But as the brush is projected onto ground, it cannot reach those instances anymore to clean them up.

**Describe a feature you consider and how it will help you**
I guess there could be multiple ways to solve this.
-The most hardcore way (that substance painter afaik uses to reapply edits to a changed mesh): remember each brush stroke and add an option to replay the sequence of actions.
-The most naîve option: reproject instances of a selected type a specific distance downwards.
-Or more viable options:
  -Make the brush (sphere) detachable (and in detached state positionable via transform-gizmos) with a button to apply on click
  -Add an automated way to delete instances that are a certain radius apart from potential ground or other geometry in general

**Describe alternatives you've considered**
Not using an addon for foliage placement

**Describe how you imagine it would work. With code, pseudo-code, diagram or a drawing**
I think each option already kind of explains itself

**Comment by dreadpon** [comment]
Okay, so here are the options:

1. Implement a full-blown selection tool (see circle select in Blender) and delete the selected instances.
2. Add a 'remove flying instances' button, that performs a raycast to instance origin to see if there's ground underneath and deletes the instances.

Option 1 seems the most proper one. Buuuut it might be beyond the scope of a 1.1.0 version. I will assign it for now, but I might move it to 2.0.0 instead (which will probably happen once Godot 4.0 is released and stable)

**Comment by dreadpon** [comment]
So, the prototype I made looks good. 

1. This algorithm creates a square brush view frustum
2. Iterates over octree nodes 
3. Unprojects inidividual objects on the screen 
4. Finally it rejects those outside the circle area (since frustrum tests use a square shape)

![Spatial Gardener Frustum Selection Test](https://user-images.githubusercontent.com/35217125/184831968-558f8e7c-c1f2-4800-bf48-e7ea7f2fbd5d.gif)

An actual implementation will take some time though.
