### ISSUE TITLE
[Minor Bug] Version 1.3.3 not on Assetlib

### ISSUE THREAD

**Issue by HEofOttoman** [dreadpon/godot_spatial_gardener#53]
**Godot version**
4.2.2

**Plugin version**
*Specify a numerical Spatial Gardener version you are using. Include Git commit hash if possible.*
Example:
None currently, but was using 1.3.1. Deleted and went to the assetlib to try and update, but it seems that the latest version is 1.3.2

**Platform**
*What platform you were using, when you encountered this bug?*
Example:
Windows 11

**Issue description**
In the assetlib, it says that the version of Spatial Gardener on the assetlib is 1.3.2. I'm sorry if this is not too much of an issue.
![image](https://github.com/dreadpon/godot_spatial_gardener/assets/145900606/207eea7d-5173-44e8-86b5-9ec679ac6116)
Taken on 21/5/2024

**Steps to Reproduce**
*Describe steps for others to reproduce this issue*
Example:
"1. Open Godot
2.  Click on Assetlib
3. Search for "Spatial Gardener"
4. Click on "Spatial Gardener
5. Observe the version number: 1.3.2
![image](https://github.com/dreadpon/godot_spatial_gardener/assets/145900606/65230642-12ac-4082-9223-5646a480468d)

**Minimal reproduction project**
*If applicable, please paste a link to minimal reproduction project that shows this issue in action.*

**Comment by dreadpon** [comment]
Thank you for noticing!
The download link on AssetLib leads to 1.3.3, but the version in description was not updated. Submitted the edit request, should be updated shortly
