### ISSUE TITLE
[BUG] Can't paint foliage at all in Godot v3.4.4 stable mono official on Windows 11

### ISSUE THREAD

**Issue by Datenheld** [dreadpon/godot_spatial_gardener#7]
**v3.4.4 stable mono official (419e713a2)**

**Gardener 1.0.0**

**Windows 11**

**Issue description**
Foliage cannot be painted. I setup Gardner according to the documentation, set collision layers, add a mesh and try to drag with the left mouse button in the viewport. Nothing happens, the bubble does not move at all. I can however resize the bubble via right click and drag.

**Steps to Reproduce**
Create a new Gardener object in the scene
Add a mesh. I add an obj file, as I don't have mesh files - the file filter does not permit it but it seems to be displayed properly in the small preview rectangle. 
Select the mesh as foliage and try to paint it by left clicking and dragging - nothing happens, the bubble won't even move. No errors are displayed in the console.

**Comment by geowarin** [comment]
Did you set up collisions for your mesh?

**Comment by dreadpon** [comment]
Yes, please make sure you've set up a Physics Body (preferably static) and collision shapes (with proper layers) for you landscape.

**Comment by dreadpon** [comment]
I have tested painting using a demo project included in `Releases`, and had no trouble whatsoever.
Report if you still experience this issue after setting up the landscape body+collision.

**Comment by Datenheld** [comment]
Thanks, setting up a static body with a collision shape solved the problem. Sorry for the false positive.
